project:
  type: website
  output-dir: docs

website:
  title: "Green Space Inequality in Washington, D.C."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: method.qmd
        text: Methods
      - href: analysis.qmd
        text: Analysis
      - href: conclusion.qmd
        text: Conclusion

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
